### ISSUE TITLE
docs: Issue in page API Documentation - add links, content

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb-cloud-doc-issues#10]
I would like to report an issue in page https://cloud.docs.scylladb.com/master/api-docs/index

Add a link to the Scylla Cloud Terraform provider https://cloud.docs.scylladb.com/stable/terraform-provider/
Trreaform is an easier way to consum the API

**Comment by tzach** [comment]
The other direction is missing as well to use the [Terrafrom provider](https://cloud.docs.scylladb.com/stable/terraform-provider/) one need to have a Token for the [Cloud API](https://cloud.docs.scylladb.com/master/api-docs/index)

**Comment by annastuchlik** [comment]
Good catch, thanks! The token is mentioned in the tutorial but not on the documentation page for Terraform Provider.
