### ISSUE TITLE
docs: Issue in page Deploy ScyllaDB Cloud to Your Own AWS Account

### ISSUE THREAD

**Issue by scylladb-buff** [scylladb/scylladb-cloud-doc-issues#17]
I would like to report an issue in page https://cloud.docs.scylladb.com/master/cloud-setup/scylla-cloud-byoa

### Problem
"AWS Account Limits
Make sure you add the following limits to your AWS account for the resources ScyllaDB Cloud will use. Please make sure that you repeat the resource allocation for each region you plan to use. Note that the following numbers should be in addition to your existing resource allocation.

Use AWS Service Quotas to increase the following resources limits:"

###  Suggest a fix

We should clarify that those limits are recommendations. 
Idea for copy:
"To ensure that you don't exceed your AWS account quota, we suggest setting a specific quota for the resources that ScyllaDB Cloud will use. These quotas should be adjusted for each region where you intend to operate. Please note that the recommended limits should be considered in addition to your current resource allocation."

### Problem

Amazon Elastic Compute Cloud (Amazon EC2) 200 EC2-VPC Elastic IPs

###  Suggest a fix
Reduce them to 20 (10 times less)
Amazon Elastic Compute Cloud (Amazon EC2) 20 EC2-VPC Elastic IPs

@mixellent any concerns with the above changes?

**Comment by annastuchlik** [comment]
I'll update the wording if those are recommendations.
@mixellent Can you confirm that the above limit should be reduced as @scylladb-buff suggested? There must be a reason it was originally added, so I'd rather double-check.
Should we verify this with the dev team?

**Comment by mixellent** [comment]
Looks good to me. This is after we had checked this with DevOps
