### ISSUE TITLE
docs: Issue on page Quick Start Guide to ScyllaDB Cloud

### ISSUE THREAD

**Issue by pogzie** [scylladb/scylladb-cloud-doc-issues#21]
I would like to report an issue on page https://cloud.docs.scylladb.com/master/scylladb-quickstart/index

### Problem

We have two customers asking to have a larger range in the IP address CIDR (ie `/14` range) instead of the allowed `/16`. 

###  Suggest a fix

Add information in the documentation to discuss the `/16` limit and also recommend a workaround that if they would want a `/14` it is possible to add 4 entries for `/16` range (would be equal to the `/14` they require)

**Comment by tzach** [comment]
@pogzie 
is this a doc issue or a feature request (larger range in the IP address) ?

**Comment by annastuchlik** [comment]
@omrivardi Please have a look at this issue. I need your input to decide if this is a documentation issue at all.
If it is, please specify how to describe the workaround.

**Comment by tzach** [comment]
@gmizrahi which team own this? AFAIU, its not just a fornt end issue.

**Comment by omrivardi** [comment]
IMO this is not a documentation issue, not aware of any other such request in the past and not sure if that is common.
For the feature request, it is relevant for siren

**Comment by gmizrahi** [comment]
This is a very uncommon request; use a /14 (!??); any person with basic network knowledge will know that 4 x /16 = 1 x /14.
I don't see any reason and logic why to add this information to any document and suggest to close the issue/request

**Comment by annastuchlik** [comment]
@pogzie I'm closing this issue following the discussion above.
If needed, please create an issue in the https://github.com/scylladb/siren repo. Thanks.
