### ISSUE TITLE
docs: Issue on page Scaling a Cluster

### ISSUE THREAD

**Issue by pogzie** [scylladb/scylladb-cloud-doc-issues#24]
I would like to report an issue on page https://cloud.docs.scylladb.com/master/manage-clusters/scylla-cloud-scale-cluster

### Problem

While the document mentions the ability to request instance type change requests, there is a limitation that customers wont be able to change to t3.micro instances.

###  Suggest a fix

We need to put this limitation in the documentation. There is an instance where a customer is done testing their staging environment and wants to change the instance type to something smaller. We have informed them that t3s should not be used.

**Comment by annastuchlik** [comment]
I'll add the information, but I'm not sure if I understand the case. Why would anyone want to resize to t3.micro?
In the application, there's the following information for t3.micro:
![Image](https://github.com/user-attachments/assets/6dd417b2-60c6-4843-8d83-eeeed49f7229)
So there are many more limitations than just resize options.

**Comment by mixellent** [comment]
@annastuchlik the same limitation is valid for e2.micro instance (GCP equivalent)

**Comment by annastuchlik** [comment]
> [@annastuchlik](https://github.com/annastuchlik) the same limitation is valid for e2.micro instance (GCP equivalent)

I've updated https://github.com/scylladb/scylla-cloud-doc/pull/243. Please review.
