### ISSUE TITLE
docs: Issue in page ScyllaDB Basics (small typo)

### ISSUE THREAD

**Issue by BroccoliHijinx** [scylladb/scylladb-cloud-doc-issues#4]
I would like to report an issue in page https://cloud.docs.scylladb.com/master/scylladb-basics/index

### Problem

Small typo which states "ScyllDB" (missing a) under "How do I interact with a ScyllaDB cluster?"

###  Suggest a fix

Add the 'a' :)

**Comment by annastuchlik** [comment]
@BroccoliHijinx Thanks for reporting! The issue is now fixed.
