### ISSUE TITLE
docs: Issue in page Get Free Trial

### ISSUE THREAD

**Issue by vebz** [scylladb/scylladb-cloud-doc-issues#9]
I would like to report an issue in page https://cloud.docs.scylladb.com/master/evaluation/index

### Problem
Doesn't specify the duration

###  Suggest a fix
Please add details of the free trials such as duration

**Comment by annastuchlik** [comment]
@vebz Thank you for opening this issue.
We're currently implementing a new trial offering, and we'll make sure that the trial duration is specified in the ScyllaDB Cloud docs.

**Comment by annastuchlik** [comment]
The new trial is now available. We do not specify the duration in the docs, as it depends on the cluster configuration selected for the trial. The information is displayed directly on the trial page and the trial cluster page.
